### ISSUE TITLE
CMake Error at ros_kortex/kortex_driver/cmake/conan.cmake:399 (message):   Conan install failed='1'

### ISSUE THREAD

**Issue by BADAL244** [Kinovarobotics/ros_kortex#241]
-- +++ processing catkin package: 'kortex_driver'
-- ==> add_subdirectory(ros_kortex/kortex_driver)
CONAN_TARGET_PLATFORM is jetson
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Generating .msg files for action kortex_driver/FollowCartesianTrajectory /home/wasp2/catkin_ws/src/ros_kortex/kortex_driver/action/non_generated/FollowCartesianTrajectory.action
-- kortex_driver: 432 messages, 259 services
-- Conan: checking conan executable in path
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 1.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('MarkupSafe>=2.0'), {{'Jinja2'}})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'MarkupSafe>=2.0' distribution was not found and is required by Jinja2

-- Conan: Adding kinova_public remote repository (https://artifactory.kinovaapps.com/artifactory/api/conan/conan-public)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 1.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('MarkupSafe>=2.0'), {{'Jinja2'}})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'MarkupSafe>=2.0' distribution was not found and is required by Jinja2
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=7;-s;compiler.libcxx=libstdc++11;-s;kortex_api_cpp:arch=armv7;-s;kortex_api_cpp:compiler=gcc;-s;kortex_api_cpp:compiler.version=7;-s;kortex_api_cpp:compiler.libcxx=libstdc++11
-- Conan executing: conan install /home/wasp2/catkin_ws/src/ros_kortex/kortex_driver/conanfile.py -s build_type=Release -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++11 -s kortex_api_cpp:arch=armv7 -s kortex_api_cpp:compiler=gcc -s kortex_api_cpp:compiler.version=7 -s kortex_api_cpp:compiler.libcxx=libstdc++11 -e=TARGET=jetson -g=cmake --update
Traceback (most recent call last):
  File "/home/wasp2/.local/bin/conan", line 11, in <module>
    load_entry_point('conan==1.48.2', 'console_scripts', 'conan')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/conan.py", line 7, in <module>
    from conans.client.command import main
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/command.py", line 16, in <module>
    from conans.client.conan_api import Conan, default_manifest_folder, _make_abs_path, ProfileData
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/conan_api.py", line 13, in <module>
    from conans.client.cmd.create import create
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/cmd/create.py", line 3, in <module>
    from conans.client.cmd.test import install_build_and_test
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/cmd/test.py", line 6, in <module>
    from conans.client.manager import deps_install
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/manager.py", line 7, in <module>
    from conans.client.installer import BinaryInstaller, call_system_requirements
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/installer.py", line 11, in <module>
    from conans.client.generators import TXTGenerator, write_toolchain
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/generators/__init__.py", line 23, in <module>
    from .markdown import MarkdownGenerator
  File "/home/wasp2/.local/lib/python2.7/site-packages/conans/client/generators/markdown.py", line 8, in <module>
    from conan.tools.cmake.cmakedeps.cmakedeps import CMakeDeps
  File "/home/wasp2/.local/lib/python2.7/site-packages/conan/tools/cmake/__init__.py", line 1, in <module>
    from conan.tools.cmake.toolchain.toolchain import CMakeToolchain
  File "/home/wasp2/.local/lib/python2.7/site-packages/conan/tools/cmake/toolchain/toolchain.py", line 12, in <module>
    from conan.tools.cmake.toolchain.blocks import ToolchainBlocks, UserToolchain, GenericSystemBlock, \
  File "/home/wasp2/.local/lib/python2.7/site-packages/conan/tools/cmake/toolchain/blocks.py", line 9, in <module>
    from conan.tools.apple.apple import is_apple_os, to_apple_arch
  File "/home/wasp2/.local/lib/python2.7/site-packages/conan/tools/apple/__init__.py", line 8, in <module>
    from conan.tools.apple.apple import fix_apple_shared_install_name
  File "/home/wasp2/.local/lib/python2.7/site-packages/conan/tools/apple/apple.py", line 170
    command = f"install_name_tool {{dylib_path}} -id {{new_name}}"
                                                             ^
SyntaxError: invalid syntax
CMake Error at ros_kortex/kortex_driver/cmake/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  ros_kortex/kortex_driver/cmake/conan.cmake:485 (conan_cmake_install)
  ros_kortex/kortex_driver/CMakeLists.txt:92 (conan_cmake_run)

-- Configuring incomplete, errors occurred!
See also "/home/wasp2/catkin_ws/build/CMakeFiles/CMakeOutput.log".

**Comment by BADAL244** [comment]
I have solved the error , in my package kortex api was empty. i downloaded the kortex api and keep the lib and include file there . now its build properly .
